-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  content text NOT NULL,
  priority text DEFAULT 'normal'::text,
  status text DEFAULT 'pending'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.asset_issue_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  employee_inventory_id uuid,
  issue_description text NOT NULL,
  issue_image_url text,
  requested_action USER-DEFINED NOT NULL DEFAULT 'evaluate'::asset_requested_action,
  admin_decision USER-DEFINED,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  issue_quantity integer NOT NULL DEFAULT 1 CHECK (issue_quantity > 0),
  CONSTRAINT asset_issue_requests_pkey PRIMARY KEY (id),
  CONSTRAINT asset_issue_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT asset_issue_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT asset_issue_requests_employee_inventory_id_fkey FOREIGN KEY (employee_inventory_id) REFERENCES public.employee_inventory(id)
);
CREATE TABLE public.asset_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  asset_type text NOT NULL,
  quantity integer DEFAULT 1,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  asset_specification text,
  CONSTRAINT asset_requests_pkey PRIMARY KEY (id),
  CONSTRAINT asset_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT asset_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  date date NOT NULL,
  shift_id uuid,
  check_in time without time zone,
  check_out time without time zone,
  status text DEFAULT 'present'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_logs_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id)
);
CREATE TABLE public.attendance_regularization_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  date date NOT NULL,
  actual_time time without time zone,
  requested_time time without time zone NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_regularization_requests_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_regularization_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT attendance_regularization_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bank_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  routing_number text,
  account_holder_name text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::verification_status,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_details_pkey PRIMARY KEY (id),
  CONSTRAINT bank_details_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT bank_details_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bin_inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  general_inventory_id uuid NOT NULL,
  item_name text NOT NULL,
  category text NOT NULL,
  serial_number text,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric,
  total_value numeric DEFAULT ((quantity)::numeric * COALESCE(unit_price, (0)::numeric)),
  reason text NOT NULL,
  disposal_date date DEFAULT CURRENT_DATE,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT bin_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT bin_inventory_general_inventory_id_fkey FOREIGN KEY (general_inventory_id) REFERENCES public.general_inventory(id),
  CONSTRAINT bin_inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  calendar_id uuid NOT NULL,
  created_by uuid,
  title text NOT NULL,
  description text,
  location text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  is_all_day boolean DEFAULT false,
  timezone text DEFAULT 'UTC'::text,
  is_recurring boolean DEFAULT false,
  recurrence_rule text,
  recurrence_end_date timestamp with time zone,
  parent_event_id uuid,
  status USER-DEFINED DEFAULT 'confirmed'::event_status,
  visibility USER-DEFINED DEFAULT 'internal'::event_visibility,
  google_event_id text,
  external_event_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_calendar_id_fkey FOREIGN KEY (calendar_id) REFERENCES public.calendars(id),
  CONSTRAINT calendar_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT calendar_events_parent_event_id_fkey FOREIGN KEY (parent_event_id) REFERENCES public.calendar_events(id)
);
CREATE TABLE public.calendar_integrations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  calendar_id uuid,
  provider USER-DEFINED NOT NULL,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  external_calendar_id text,
  external_account_email text,
  sync_enabled boolean DEFAULT true,
  sync_direction text DEFAULT 'two_way'::text,
  last_sync_at timestamp with time zone,
  next_sync_at timestamp with time zone,
  sync_token text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT calendar_integrations_calendar_id_fkey FOREIGN KEY (calendar_id) REFERENCES public.calendars(id)
);
CREATE TABLE public.calendar_shares (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  calendar_id uuid,
  shared_with_user_id uuid,
  shared_by_user_id uuid,
  can_view boolean DEFAULT true,
  can_edit boolean DEFAULT false,
  can_delete boolean DEFAULT false,
  can_share boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_shares_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_shares_calendar_id_fkey FOREIGN KEY (calendar_id) REFERENCES public.calendars(id),
  CONSTRAINT calendar_shares_shared_with_user_id_fkey FOREIGN KEY (shared_with_user_id) REFERENCES public.profiles(id),
  CONSTRAINT calendar_shares_shared_by_user_id_fkey FOREIGN KEY (shared_by_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.calendar_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  calendar_id uuid,
  user_id uuid,
  subscription_token text NOT NULL UNIQUE,
  feed_url text NOT NULL,
  is_active boolean DEFAULT true,
  include_private_events boolean DEFAULT false,
  refresh_interval_minutes integer DEFAULT 15,
  last_accessed_at timestamp with time zone,
  access_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_subscriptions_calendar_id_fkey FOREIGN KEY (calendar_id) REFERENCES public.calendars(id),
  CONSTRAINT calendar_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.calendar_sync_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  integration_id uuid,
  sync_status USER-DEFINED NOT NULL,
  direction text,
  events_synced integer DEFAULT 0,
  events_created integer DEFAULT 0,
  events_updated integer DEFAULT 0,
  events_deleted integer DEFAULT 0,
  error_message text,
  error_details jsonb,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  duration_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_sync_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.calendar_integrations(id)
);
CREATE TABLE public.calendars (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  type USER-DEFINED NOT NULL DEFAULT 'personal'::calendar_type,
  owner_id uuid,
  department_id uuid,
  color text DEFAULT '#3B82F6'::text,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  timezone text DEFAULT 'UTC'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendars_pkey PRIMARY KEY (id),
  CONSTRAINT calendars_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT calendars_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.covering_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  hours_to_cover numeric NOT NULL CHECK (hours_to_cover >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT covering_hours_pkey PRIMARY KEY (id),
  CONSTRAINT covering_hours_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.covering_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  covering_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  work_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  attachment_type text CHECK (attachment_type = ANY (ARRAY['commit_link'::text, 'file_upload'::text])),
  commit_link text,
  covering_files jsonb,
  proof_submitted_at timestamp without time zone,
  work_verified_at timestamp without time zone,
  verified_by uuid,
  CONSTRAINT covering_requests_pkey PRIMARY KEY (id),
  CONSTRAINT covering_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT covering_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT covering_requests_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  head_id uuid,
  parent_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_head_id_fkey FOREIGN KEY (head_id) REFERENCES public.profiles(id),
  CONSTRAINT departments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.departments(id)
);
CREATE TABLE public.designations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  department_id uuid,
  level integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT designations_pkey PRIMARY KEY (id),
  CONSTRAINT designations_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.document_access (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid,
  user_id uuid,
  can_view boolean DEFAULT true,
  can_edit boolean DEFAULT false,
  can_delete boolean DEFAULT false,
  granted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_access_pkey PRIMARY KEY (id),
  CONSTRAINT document_access_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT document_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.document_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  color text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  request_type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::document_request_status,
  fulfilled_by uuid,
  fulfilled_at timestamp with time zone,
  rejection_reason text,
  document_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_requests_pkey PRIMARY KEY (id),
  CONSTRAINT document_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT document_requests_fulfilled_by_fkey FOREIGN KEY (fulfilled_by) REFERENCES public.profiles(id),
  CONSTRAINT document_requests_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_tags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid,
  tag text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_tags_pkey PRIMARY KEY (id),
  CONSTRAINT document_tags_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL,
  version_number integer NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  uploaded_by uuid NOT NULL,
  change_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT document_versions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  uploaded_by uuid,
  title text NOT NULL,
  description text,
  file_url text NOT NULL,
  file_type text,
  file_size integer,
  category text,
  is_public boolean DEFAULT false,
  expiry_date date,
  version integer DEFAULT 1,
  parent_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_id uuid,
  request_id uuid,
  tags ARRAY,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.documents(id),
  CONSTRAINT documents_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.document_categories(id),
  CONSTRAINT documents_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.document_requests(id)
);
CREATE TABLE public.employee_education (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  degree text NOT NULL,
  institution text NOT NULL,
  field_of_study text,
  start_year integer,
  end_year integer,
  grade text,
  created_at timestamp with time zone DEFAULT now(),
  isverified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  CONSTRAINT employee_education_pkey PRIMARY KEY (id),
  CONSTRAINT employee_education_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_education_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  item_name text NOT NULL,
  item_type text,
  serial_number text,
  assigned_date date DEFAULT CURRENT_DATE,
  return_date date,
  condition text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_id uuid,
  isverified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  general_inventory_id uuid,
  quantity_assigned integer DEFAULT 1 CHECK (quantity_assigned > 0),
  condition_image_url text,
  CONSTRAINT employee_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT employee_inventory_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_inventory_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.inventory_categories(id),
  CONSTRAINT employee_inventory_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT employee_inventory_general_inventory_id_fkey FOREIGN KEY (general_inventory_id) REFERENCES public.general_inventory(id)
);
CREATE TABLE public.employee_leave_balance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  policy_id uuid NOT NULL,
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  year integer NOT NULL CHECK (year >= 2020),
  total_leaves numeric NOT NULL DEFAULT 0,
  used_leaves numeric NOT NULL DEFAULT 0,
  available_leaves numeric NOT NULL DEFAULT 0,
  carried_forward_leaves numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_leave_balance_pkey PRIMARY KEY (id),
  CONSTRAINT employee_leave_balance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_leave_balance_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.employee_policies(id)
);
CREATE TABLE public.employee_policies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  policy_type USER-DEFINED NOT NULL,
  working_days_per_week integer NOT NULL CHECK (working_days_per_week >= 1 AND working_days_per_week <= 7),
  leave_days_per_month numeric NOT NULL DEFAULT 0 CHECK (leave_days_per_month >= 0::numeric),
  carry_forward_enabled boolean DEFAULT true,
  renewal_period USER-DEFINED DEFAULT 'yearly'::renewal_period,
  description text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  working_start_time time without time zone NOT NULL DEFAULT '09:00:00'::time without time zone,
  working_end_time time without time zone NOT NULL DEFAULT '18:00:00'::time without time zone,
  CONSTRAINT employee_policies_pkey PRIMARY KEY (id),
  CONSTRAINT employee_policies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_skills (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  skill_name text NOT NULL,
  proficiency_level integer CHECK (proficiency_level >= 1 AND proficiency_level <= 5),
  years_of_experience integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_skills_pkey PRIMARY KEY (id),
  CONSTRAINT employee_skills_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL,
  employee_id text NOT NULL UNIQUE,
  department_id uuid,
  designation_id uuid,
  supervisor_id uuid,
  date_of_birth date,
  gender USER-DEFINED,
  blood_group USER-DEFINED,
  marital_status USER-DEFINED,
  joining_date date NOT NULL,
  address text,
  city text,
  state text,
  postal_code text,
  country text DEFAULT 'USA'::text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  policy_id uuid,
  policy_assigned_date date,
  is_active boolean DEFAULT true,
  employee_no character varying UNIQUE,
  isverified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id),
  CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT employees_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES public.designations(id),
  CONSTRAINT employees_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.profiles(id),
  CONSTRAINT employees_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.employee_policies(id),
  CONSTRAINT employees_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.event_attendees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid,
  user_id uuid,
  email text,
  response_status text DEFAULT 'pending'::text,
  is_organizer boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendees_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.calendar_events(id),
  CONSTRAINT event_attendees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.event_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid,
  user_id uuid,
  minutes_before integer NOT NULL,
  method text DEFAULT 'notification'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT event_reminders_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.calendar_events(id),
  CONSTRAINT event_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.expense_reimbursements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  expense_type text NOT NULL,
  amount numeric NOT NULL,
  expense_date date NOT NULL,
  description text NOT NULL,
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  attachments jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT expense_reimbursements_pkey PRIMARY KEY (id),
  CONSTRAINT expense_reimbursements_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT expense_reimbursements_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.general_inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_name text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['furniture'::text, 'equipment'::text, 'supplies'::text, 'electronics'::text, 'appliances'::text, 'tools'::text, 'vehicles'::text, 'other'::text])),
  description text,
  serial_number text UNIQUE,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  unit_price numeric CHECK (unit_price >= 0::numeric),
  total_value numeric DEFAULT ((quantity)::numeric * unit_price),
  location text,
  condition text CHECK (condition = ANY (ARRAY['new'::text, 'good'::text, 'fair'::text, 'poor'::text, 'damaged'::text])),
  status text NOT NULL DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'in-use'::text, 'maintenance'::text, 'retired'::text, 'disposed'::text])),
  purchase_date date,
  warranty_expiry date,
  supplier text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  last_updated_by uuid,
  image_url text,
  CONSTRAINT general_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT general_inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT general_inventory_last_updated_by_fkey FOREIGN KEY (last_updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.holidays (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  date date NOT NULL,
  is_optional boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.kyc_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  document_type text NOT NULL,
  document_number text,
  document_url text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::verification_status,
  verified_by uuid,
  verified_at timestamp with time zone,
  expiry_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sub_type text,
  document_title text,
  CONSTRAINT kyc_documents_pkey PRIMARY KEY (id),
  CONSTRAINT kyc_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT kyc_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  leave_type USER-DEFINED NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days numeric NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  start_time time without time zone,
  end_time time without time zone,
  leave_duration character varying,
  covering_decision text,
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.login_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  login_time timestamp with time zone DEFAULT now(),
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  CONSTRAINT login_history_pkey PRIMARY KEY (id),
  CONSTRAINT login_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.maintenance_inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  general_inventory_id uuid NOT NULL,
  item_name text NOT NULL,
  category text NOT NULL,
  serial_number text,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric,
  total_value numeric DEFAULT ((quantity)::numeric * COALESCE(unit_price, (0)::numeric)),
  issue_description text NOT NULL,
  repair_notes text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::maintenance_status,
  expected_completion_date date,
  actual_completion_date date,
  moved_to_maintenance_date date DEFAULT CURRENT_DATE,
  returned_to_inventory_date date,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_updated_by uuid,
  source_employee_id uuid,
  source_employee_inventory_id uuid,
  CONSTRAINT maintenance_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_inventory_general_inventory_id_fkey FOREIGN KEY (general_inventory_id) REFERENCES public.general_inventory(id),
  CONSTRAINT maintenance_inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT maintenance_inventory_last_updated_by_fkey FOREIGN KEY (last_updated_by) REFERENCES public.profiles(id),
  CONSTRAINT maintenance_inventory_source_employee_id_fkey FOREIGN KEY (source_employee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  leave_updates boolean DEFAULT true,
  attendance_alerts boolean DEFAULT true,
  meeting_reminders boolean DEFAULT true,
  announcements boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  read boolean DEFAULT false,
  link text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.overtime_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  date date NOT NULL,
  hours numeric NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  assigned_supervisor uuid,
  CONSTRAINT overtime_requests_pkey PRIMARY KEY (id),
  CONSTRAINT overtime_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT overtime_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT overtime_requests_assigned_supervisor_fkey FOREIGN KEY (assigned_supervisor) REFERENCES public.profiles(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  resource text NOT NULL,
  action text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'employee'::user_role,
  avatar_url text,
  phone text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.request_for_covering_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT request_for_covering_requests_pkey PRIMARY KEY (id),
  CONSTRAINT request_for_covering_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT request_for_covering_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  request_type USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::request_status,
  submitted_at timestamp with time zone DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.resignations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  last_working_date date NOT NULL,
  reason text NOT NULL,
  feedback text,
  created_at timestamp with time zone DEFAULT now(),
  document_url text,
  CONSTRAINT resignations_pkey PRIMARY KEY (id),
  CONSTRAINT resignations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT resignations_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role_id uuid,
  permission_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  is_system_role boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.salaries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid UNIQUE,
  base_amount numeric NOT NULL,
  currency text DEFAULT 'LKR'::text,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  recurring_allowances jsonb DEFAULT '[]'::jsonb,
  recurring_deductions jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT salaries_pkey PRIMARY KEY (id),
  CONSTRAINT salaries_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.salary_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  month character varying NOT NULL,
  base_amount numeric NOT NULL,
  gross_amount numeric NOT NULL,
  net_amount numeric NOT NULL,
  additions jsonb DEFAULT '[]'::jsonb,
  deductions jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'draft'::text,
  payment_date date,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  employee_status text DEFAULT 'pending'::text CHECK (employee_status = ANY (ARRAY['pending'::text, 'approved'::text, 'disputed'::text])),
  dispute_reason text,
  employee_approved_at timestamp with time zone,
  admin_approval_status text DEFAULT 'pending'::text CHECK (admin_approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_approved_at timestamp with time zone,
  admin_approved_by uuid,
  CONSTRAINT salary_payments_pkey PRIMARY KEY (id),
  CONSTRAINT salary_payments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT salary_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT salary_payments_admin_approved_by_fkey FOREIGN KEY (admin_approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shifts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.travel_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  employee_id uuid,
  destination text NOT NULL,
  purpose text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  estimated_cost numeric,
  created_at timestamp with time zone DEFAULT now(),
  check_out_time time without time zone,
  check_in_time time without time zone,
  CONSTRAINT travel_requests_pkey PRIMARY KEY (id),
  CONSTRAINT travel_requests_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id),
  CONSTRAINT travel_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  role_id uuid,
  granted_by uuid,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT user_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.visitors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name text NOT NULL,
  email text,
  phone text,
  identification_id text,
  company_name text,
  purpose text NOT NULL,
  host_employee_id uuid,
  scheduled_arrival timestamp with time zone NOT NULL,
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  status USER-DEFINED DEFAULT 'scheduled'::visitor_status,
  badge_number text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visitors_pkey PRIMARY KEY (id),
  CONSTRAINT visitors_host_employee_id_fkey FOREIGN KEY (host_employee_id) REFERENCES public.employees(id),
  CONSTRAINT visitors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);